version = 0.1

[default.deploy.parameters]
stack_name = "adot-serverless-demo-otel"
resolve_s3 = true
s3_prefix = "adot-serverless-demo-otel"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "SlowModeDelaySeconds=6",
    "NodeAdotLayerArn=arn:aws:lambda:us-east-1:615299751070:layer:AWSOpenTelemetryDistroJs:13",
    "PythonAdotLayerArn=arn:aws:lambda:us-east-1:615299751070:layer:AWSOpenTelemetryDistroPython:25",
    "OtelBackendSecretName=adot-serverless-demo-otel-backend",
    "OtelBackendConfigVersion=2026-03-19-1",
]
image_repositories = []

[default.global.parameters]
region = "us-east-1"
